### ISSUE TITLE
How to use FS2 Streams to stream data via the gRPC calls?

### ISSUE THREAD

**Issue by skulos** [higherkindness/mu-scala#1163]
I don't complete get the FS2 Streams as the RPC streams.

I want to stream a file to the server implementation, which is in Go, and works. But the client sub needs to be in Scala, preferably with Cats-effect. Hence, Mu-Scala.

I've followed the examples, and I've "muSrcGen" my Protobuf definitions, and I've gotten the code. The function is a bi-directional stream. I stream from the client, and get back a stream. But now, if I use  a IOApp to make the calls, I get a unavailable channel error. And I can't touch the Stream after the function call or the program error out.

I've code the server, in go, to print out logs if a client connects and makes a RPC. I've tested this with a test-client, also in Go, and it works. But when I run the IOApp I don't see the logs. And if the run function makes the call (or at least that's what is suppose to happen) and finishes, not logs.

I'm slightly confused. Do I need to compile the stream I get out of the function call? Not that it's populated with anything. SInce I can't find a valid streaming example, I'd like to ask here. My code is as follow:

`hello.proto`
```
// Proto version
syntax = "proto3";

// Package name
package test;

message Requests {
  string data = 1;
}

message Responses {
  string data = 1;
}

service StreamsTest {
  rpc TestStream (stream Requests) returns (stream Responses);
  rpc TestUnary (Requests) returns ( Responses);
}
```

`target/scala-2.13/src_managed/main/test/hello.scala`
```
package test
import _root_.higherkindness.mu.rpc.protocol._
object hello {
  final case class Requests(@_root_.pbdirect.pbIndex(1) data: _root_.java.lang.String)
  final case class Responses(@_root_.pbdirect.pbIndex(1) data: _root_.java.lang.String)
  @service(Protobuf, compressionType = Identity, namespace = Some("test")) trait StreamsTest[F[_]] {
    def TestStream(req: _root_.fs2.Stream[F, _root_.test.hello.Requests]): F[_root_.fs2.Stream[F, _root_.test.hello.Responses]]
    def TestUnary(req: _root_.test.hello.Requests): F[_root_.test.hello.Responses]
  }
}
```

`Client.scala`
```
object Client extends IOApp {

  val channelFor: ChannelFor = ChannelForAddress("localhost", 7070)
  val serviceClient: Resource[IO, StreamsTest[IO]] = StreamsTest.client(channelFor)
  val streamIO: Stream[IO, Requests] =
    io.file
      .readAll[IO](
        Paths.get("/home/hendreh/chunkeralgorithm/src/main/resources/values"),
        Blocker.liftExecutionContext(this.executionContext),
        4096
      )
      .map(c => Requests(c.toString))

  def run(args: List[String]): IO[ExitCode] = for {

    streamResponse <- serviceClient.use(c => c.TestStream(streamIO))
    list <- streamResponse.compile.toList
    _ <- IO(println(list))
    _ <- IO(println("Done"))

  } yield {
    ExitCode.Success
  }
}
```

`ERROR`
```/home/hendreh/.jdks/openjdk-15.0.2/bin/...

io.grpc.StatusRuntimeException: UNAVAILABLE: Channel shutdown invoked
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at org.lyranthe.fs2_grpc.java_runtime.client.Fs2StreamClientCallListener.$anonfun$stream$1(Fs2StreamClientCallListener.scala:31)
	at org.lyranthe.fs2_grpc.java_runtime.client.Fs2StreamClientCallListener.$anonfun$stream$1$adapted(Fs2StreamClientCallListener.scala:27)
	at fs2.Pull$.$anonfun$flatMap$1(Pull.scala:82)
	at fs2.internal.FreeC$$anon$1.cont(Algebra.scala:53)
	at fs2.internal.FreeC$ViewL$$anon$9$$anon$10.<init>(Algebra.scala:240)
	at fs2.internal.FreeC$ViewL$$anon$9.cont(Algebra.scala:240)
	at fs2.internal.FreeC$ViewL$$anon$9$$anon$10.cont(Algebra.scala:242)
	at fs2.internal.FreeC$ViewL$.mk(Algebra.scala:231)
	at fs2.internal.FreeC$ViewL$.apply(Algebra.scala:220)
	at fs2.internal.FreeC.viewL(Algebra.scala:106)
	at fs2.internal.FreeC$.go$1(Algebra.scala:421)
	at fs2.internal.FreeC$.$anonfun$compile$10(Algebra.scala:477)
	at fs2.internal.FreeC$.$anonfun$compile$1(Algebra.scala:437)
	at flatMap @ fs2.internal.CompileScope.$anonfun$openAncestor$2(CompileScope.scala:261)
	at flatMap @ fs2.internal.FreeC$.$anonfun$compile$17(Algebra.scala:545)
	at map @ fs2.internal.CompileScope.$anonfun$close$9(CompileScope.scala:246)
	at flatMap @ fs2.internal.CompileScope.$anonfun$close$6(CompileScope.scala:245)
	at map @ fs2.internal.CompileScope.fs2$internal$CompileScope$$traverseError(CompileScope.scala:222)
	at flatMap @ fs2.internal.CompileScope.$anonfun$close$4(CompileScope.scala:244)
	at map @ fs2.internal.CompileScope.fs2$internal$CompileScope$$traverseError(CompileScope.scala:222)
	at flatMap @ fs2.internal.CompileScope.$anonfun$close$2(CompileScope.scala:242)
	at flatMap @ fs2.internal.CompileScope.close(CompileScope.scala:241)
	at flatMap @ fs2.internal.FreeC$.closeAndGo$1(Algebra.scala:544)
	at flatMap @ fs2.internal.FreeC$.go$1(Algebra.scala:568)
	at flatMap @ fs2.internal.CompileScope.$anonfun$openAncestor$2(CompileScope.scala:261)
	at flatMap @ fs2.internal.FreeC$.$anonfun$compile$17(Algebra.scala:545)
	at map @ fs2.internal.CompileScope.$anonfun$close$9(CompileScope.scala:246)
	at flatMap @ fs2.internal.CompileScope.$anonfun$close$6(CompileScope.scala:245)

Process finished with exit code 1
```

**Comment by skulos** [comment]
Any suggestions?

**Comment by cb372** [comment]
I think the problem is that you're working with the Stream after closing the client. Does this work?

```scala
object Client extends IOApp {

  val channelFor: ChannelFor = ChannelForAddress("localhost", 7070)
  val serviceClient: Resource[IO, StreamsTest[IO]] = StreamsTest.client(channelFor)
  val streamIO: Stream[IO, Requests] =
    io.file
      .readAll[IO](
        Paths.get("/home/hendreh/chunkeralgorithm/src/main/resources/values"),
        Blocker.liftExecutionContext(this.executionContext),
        4096
      )
      .map(c => Requests(c.toString))

  def run(args: List[String]): IO[ExitCode] = for {
    list <- serviceClient.use(c => c.TestStream(streamIO).flatMap(_.compile.toList))
    _ <- IO(println(list))
    _ <- IO(println("Done"))

  } yield {
    ExitCode.Success
  }
}
```

**Comment by skulos** [comment]
Yes, it does. Thank you so much. This literally rolls a huge blocker out of my path.

**Comment by skulos** [comment]
Again, thank you so much.
